language: php

sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

addons:
  postgresql: "9.3"
  apt:
    packages:
      - php5-pgsql

before_script:
  - make config/dbc.json src/db-migrations/create-database.sql
  - psql -U postgres <src/db-migrations/create-database.sql
  - psql -U postgres $(util/get-db-name) <src/db-migrations/enable-extensions.sql
  - touch .database-created
  - util/test-db-connection

script: make run-unit-tests
