language: php

sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

addons:
  postgresql: "9.3"

before_script:
  - make config/dbc.json build/db/create-database.sql
  - psql -U postgres <build/db/create-database.sql
  - psql -U postgres $(util/get-db-name) <build/db/enable-extensions.sql
  - touch .database-created

script: make run-unit-tests
